"""adicionar tipo em usuarios e trocar email por matricula

Revision ID: 24b6d63ea85d
Revises: 9bbc30f86350
Create Date: 2026-05-15 15:46:48.809675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b6d63ea85d'
down_revision = '9bbc30f86350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
