"""criando tabela disciplinas

Revision ID: 7f006d560c29
Revises: a9b6cdf099e1
Create Date: 2026-03-25 16:49:45.517902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f006d560c29'
down_revision = 'a9b6cdf099e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('carga_horaria', sa.String(length=50), nullable=False),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('plano_texto', sa.Text(), nullable=True),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
