"""trocar email por matricula em usuarios

Revision ID: 9bbc30f86350
Revises: 7f006d560c29
Create Date: 2026-05-15 14:38:32.057935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbc30f86350'
down_revision = '7f006d560c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricula', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('usuarios_email_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['matricula'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('matricula')

    # ### end Alembic commands ###
